A toggle for clearing the queue after the bot has left the channel
Yucked/Victoria pull request #166
Opened 2024-06-15 21:53 UTC by thisRandomm

In Lavalink 4.X.X the queue is managed by Lavalink itself, and becuase of that, the tracks in the queue persist even after the bot leaves the channel, and they stay there until Lavalink is restarted. I found this a little bit annoying at times, so I added a toggle in the config for whether or not the queue should be cleared upon calling Lavanode.LeaveAsync()

2024-06-16 07:02 UTC, Yucked commented
`LavaPlayerExtensions.Queue.TryRemove(voiceChannel.GuildId, out _);` should be sufficient

2024-06-16 07:04 UTC, Yucked requested changes

2024-06-16 07:04 UTC, Yucked commented on src/LavaNode.cs
Replace this with suggestion left in PR

2024-06-16 07:04 UTC, Yucked commented on src/Configuration.cs
No need for preserving  queue

2024-06-17 13:13 UTC, thisRandomm commented on src/LavaNode.cs
Replaced it accordingly

2024-06-18 03:56 UTC, Yucked approved these changes

2024-06-18 03:56 UTC, merged